### PR TITLE
feat: Default OTP Templates

### PR DESCRIPTION
**Pull request by faztp12**
- Added field `sms_otp_template` in `System Settings` beside `email_otp_template`
- Made fixture `Default Email OTP Template`
- Added `SMS Template` doctype, similar to `Email Template`
- Made fixture `Default SMS OTP Template`
- Supports multi lang
- Auto sets the templates if not present

### CODE REVIEW

**Comment by assemmarwan** [comment]
@faztp12 By supporting the multi language, the language will be based on the user generating the OTP?

And if a Guest generates the OTP it will default to English, correct?

**Comment by faztp12** [comment]
@assemmarwan yes, exactly

**Comment by assemmarwan** [comment]
I think since most of the time the OTP is generated before a user is logged in, there should be a way to specify the language (based on the frontend's language, for instance).
@faztp12 @MalikZu What do you think?

**Comment by MalikZu** [comment]
I agree, can this be accomplished for guest users?

**Comment by faztp12** [comment]
if we add a `lang` param to `generate_otp`, we could have otp in custom languages for Guests..

**Comment by assemmarwan** [comment]
I reckon let's have it verbose as an optional param to the function.

**Comment by faztp12** [comment]
So something like this would do ?
```py
def generate_otp(medium="sms", medium_id=None, sms_hash=None, purpose="login", lang="en"):
  pass
```

**Comment by assemmarwan** [comment]
@faztp12 Yes 👍

**Comment by faztp12** [comment]
@assemmarwan the translation is done by frappe's `frappe._()` function, which is available in the template context.
It will read from `Translation` doctype

**Review by assemmarwan — APPROVED** [review]

**Pull request merged**
