### PR TITLE
Thumbnail Generation

### PR DESCRIPTION
**Pull request by e-lobo**
It is best to only generate the thumbnail once on_insert of document

### CODE REVIEW

**Review by fahimalizain — APPROVED** [review]
Looks good 👍🏼

**Comment by e-lobo** [comment]
@fahimalizain @assemmarwan reminder here to merge

**Review by assemmarwan — APPROVED** [review]
Should this be merged to version-13? Or we would cherry pick this commit into version-13?

**Comment by fahimalizain** [comment]
@assemmarwan  Merge to master and cherry-pick to version-13?

**Pull request merged**
